title: Quadruped II - v1.0
summary: A place for the v1.0 files of
status: draft
tags:
- dog
- drone
- diy
- arduino
- robotics
- rasberry
- code
- quadruped
- bostondynamics
- robotdog
created_at: '2026-04-30'
external:
  cad_path: ''
  firmware_path: ''
  notes: ''
